const authors = [
  {
    authorName: "Rにしおか",
    avatarUrl: "assets/Gua2ip5u_400x400.jpg",
    twitter: "R24oka",
    github: "RN24Nishioka",
    qiita: "RN24",
    role: "Engineer",
    text: "ログイン機能、機能改善、リリースなどを担当",
  },
  {
    authorName: "ポテセン",
    avatarUrl: "assets/HxEzaw0e_400x400.jpg",
    twitter: "forelgoog",
    github: "hideaki10",
    // zenn: "",
    // qiita: "",
    role: "Engineer",
    text: "podcast機能、環境構築などを担当",
  },
  {
    authorName: "とっく",
    avatarUrl: "assets/69064290.jpg",
    website: "tokku-engineer.tech/",
    twitter: "tokkuu",
    github: "tokku5552",
    zenn: "tokku5552",
    qiita: "tokkun5552",
    role: "Engineer",
    text: "Android音楽再生機能、リファクタなどを担当",
  },
  {
    authorName: "コップ時計",
    avatarUrl: "assets/77AB6E8W_400x400.jpg",
    // twitter: "",
    github: "",
    // zenn: "",
    // qiita: "",
    role: "College student / Engineer",
    text: "ログイン機能、プライバシーポリシーなどを担当",
  },
  {
    authorName: "hndr",
    avatarUrl: "assets/53109993.jpg",
    twitter: "hndrr",
    github: "hndrr",
    zenn: "hndr",
    qiita: "hndr",
    role: "PM / UX Engineer",
    text: "要件定義、UI/UXデザイン・実装などを担当",
  },
  {
    authorName: "KBOYのFlutter大学",
    avatarUrl: "assets/FzV_BaS5_400x400.jpg",
    website: "kboyflutteruniv.com/",
    youtube: "UCReuARgZI-BFjioA8KBpjsw/",
    twitter: "kboyflutteruniv",
    instagram: "kboyflutteruniv",
    zenn: "kboy/books/ca6a9c93fd23f3",
    qiita: "organizations/kboy_flutter_univ",
    role: "Community",
    text: "が運営するFlutterアプリ開発を学ぶオンラインコミュニティ内で開発されています",
  },
];

export default authors;
